# Usa Python como base
FROM python:3.10-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY requirements.txt requirements.txt
COPY ./uploads /app/uploads
COPY . .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Establece la variable de entorno FLASK_APP
ENV FLASK_APP=backend.py

# Expone el puerto 8080
EXPOSE 8080

# Comando para iniciar la aplicación
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]
